@apiUrl=https://localhost:1338

@ordinaryUserToken=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYkBhb2wuY29tIiwic3ViIjoiYm9iQGFvbC5jb20iLCJqdGkiOiIyNWY4YmY0IiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDM0NjciLCJodHRwczovL2xvY2FsaG9zdDo0NDM2OCIsImh0dHA6Ly9sb2NhbGhvc3Q6MTMzNyIsImh0dHBzOi8vbG9jYWxob3N0OjEzMzgiXSwibmJmIjoxNzE3MzU3NTkzLCJleHAiOjE3MjUzMDYzOTMsImlhdCI6MTcxNzM1NzU5NSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.bZNpHQCbarkZcpXpQtEZuHNIGS7k7bNUcgO2VUu4z9U

@catalogItemId = PUT_THE_GUID_HERE

### Add An Issue

GET {{apiUrl}}/catalog/{{catalogItemId}}/issues
Content-Type: application/json

{
    "description": "Description of Issue"
}


