@IssueTracker.Api_HostAddress = https://localhost:1338

@bobJwt = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYkBhb2wuY29tIiwic3ViIjoiYm9iQGFvbC5jb20iLCJqdGkiOiI0YTM5MDRmZiIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjQzNDY3IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNjgiLCJodHRwOi8vbG9jYWxob3N0OjEzMzciLCJodHRwczovL2xvY2FsaG9zdDoxMzM4Il0sIm5iZiI6MTcxNzM1MzY3NywiZXhwIjoxNzI1MzAyNDc3LCJpYXQiOjE3MTczNTM2NzcsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.0q0Lpiu89Gb68TTTAVW0Jd76B9Ppa045DfunH9A2EYA


### Add an Issue

POST @IssueTracker.ApiHostAddress/issues