# For more info on HTTP files go to https://aka.ms/vs/httpfile
@apiUrl=https://localhost:1338

@ordinaryUserToken=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImJvYkBhb2wuY29tIiwic3ViIjoiYm9iQGFvbC5jb20iLCJqdGkiOiIyNWY4YmY0IiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NDM0NjciLCJodHRwczovL2xvY2FsaG9zdDo0NDM2OCIsImh0dHA6Ly9sb2NhbGhvc3Q6MTMzNyIsImh0dHBzOi8vbG9jYWxob3N0OjEzMzgiXSwibmJmIjoxNzE3MzU3NTkzLCJleHAiOjE3MjUzMDYzOTMsImlhdCI6MTcxNzM1NzU5NSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.bZNpHQCbarkZcpXpQtEZuHNIGS7k7bNUcgO2VUu4z9U

@softwareCenterUserToken=Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6InN1ZUBhb2wuY29tIiwic3ViIjoic3VlQGFvbC5jb20iLCJqdGkiOiI5YTE5MzAzNyIsInJvbGUiOiJTb2Z0d2FyZUNlbnRlciIsImF1ZCI6WyJodHRwOi8vbG9jYWxob3N0OjQzNDY3IiwiaHR0cHM6Ly9sb2NhbGhvc3Q6NDQzNjgiLCJodHRwOi8vbG9jYWxob3N0OjEzMzciLCJodHRwczovL2xvY2FsaG9zdDoxMzM4Il0sIm5iZiI6MTcxNzM1NzU1NiwiZXhwIjoxNzI1MzA2MzU2LCJpYXQiOjE3MTczNTc1NTgsImlzcyI6ImRvdG5ldC11c2VyLWp3dHMifQ.eOUM-Bd2n8y9S1g7t4yOxkjINd03PEj2iekj6iyjtK
# Members of the Software Center can add new items to our catalog of supported software.
# We have a "COLLECTION" of supported software, and we want to APPEND a new subordinate resource (DOCUMENT) to that collection.

POST {{apiUrl}}/catalog
Authorization: {{softwareCenterUserToken}}
Content-Type: application/json

{
  "title": "Jetbrains Rider",
  "description": "An Integrated Development Environment for .NET Developer on Windows, Linux, Mac"
}

###

GET {{apiUrl}}/catalog
Authorization: {{ordinaryUserToken}}
###

GET {{apiUrl}}/catalog/0d85702e-3efb-4c8d-8835-4413a7d31910
Authorization: {{ordinaryUserToken}}